apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  label:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin
