apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdb-pvc
  label:
    app: localdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin
