apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snpi
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  gapp: xaix
bases:
- localdb
- influxdb
- redis
- xaix-api
- xaix-spiconnect
- xaix-fakeplugin

